#==============================================================================
#     FICHERO: config.yml
#       AUTOR: Victor Rodriguez victor<at>vrdominguez.es
# DESCRIPCION: Fichero de configuracion para comandos del contestador. Antes
#              de comenzad, este fichero debe ser adaptado a tu configuracion
#==============================================================================

# Usuarios con acceso a comandos restringidos
administradores:
  - administrator1@example.com

# Configuraciones del comando "espacio"
espacio:
  # Poner a 1 para que muestre solo datos de espacio de carpetas que sean puntos de montaje
  solo_mountpoints: 0
  carpetas:
    - /ruta/mountpoint/defecto
    - /ruta/otro/mountpoint

# Configuracion del comando "descargas"
descargas:
  usuario: nombre_usuario
  clave: clave_usuario
  host: localhost
  ejecutable: /usr/bin/transmission-remote 
  puerto: 9091
  dominio: example.com

router:
  ip: 192.168.1.1 
  usuario: admin_telnet_router
  clave: clave_telnet_router
  prompt: RouterPrompt> 

