#==============================================================================
#     FICHERO: config.yml
#       AUTOR: Victor Rodriguez victor<at>vrdominguez.es
# DESCRIPCION: Fichero de configuracion para comandos del contestador. Antes
#              de comenzad, este fichero debe ser adaptado a tu configuracion
#==============================================================================

# Usuarios con acceso a comandos restringidos
administradores:
  - administrator1@example.com

# Configuraciones del comando "espacio"
espacio:
  # Poner a 1 para que muestre solo datos de espacio de carpetas que sean puntos de montaje
  solo_mountpoints: 0
  carpetas:
    - /ruta/mountpoint/defecto
    - /ruta/otro/mountpoint

# Configuracion del comando "descargas"
descargas:
  usuario: nombre_usuario
  clave: clave_usuario
  host: localhost
  ejecutable: /usr/bin/transmission-remote 
  puerto: 9091
  dominio: example.com

# Datos de acceso al router
router:
  ip: 192.168.1.1 
  usuario: admin_telnet_router
  clave: clave_telnet_router
  prompt: RouterPrompt> 

# Listadp de macs conocidas
macs:
  DE:V0:CE:MA:C0:00: Device0 name 
  DE:V0:CE:MA:C0:01: Device1 name 
  DE:V0:CE:MA:C0:02: Device2 name 
  DE:V0:CE:MA:C0:03: Device3 name 

# Alias para comandos
alias:
  tr:
    - Transmission
    - reiniciar
  ti:
    - Transmission
    - iniciar
  td:
    - Transmission
    - detener
